package com.example

data class WorldClockCity(
    val timezoneId: String,
    val name: String,
    val flagEmoji: String,
    val offsetDisplay: String
)

object WorldClockData {
    val allCities = listOf(
        WorldClockCity("Etc/GMT+12", "Baker Island", "🏝️", "UTC-12"),
        WorldClockCity("Pacific/Pago_Pago", "American Samoa", "🇦🇸", "UTC-11"),
        WorldClockCity("Pacific/Niue", "Niue", "🇳🇺", "UTC-11"),
        WorldClockCity("Pacific/Honolulu", "Hawaii (HST)", "🌺", "UTC-10"),
        WorldClockCity("Pacific/Tahiti", "Tahiti", "🇵🇫", "UTC-10"),
        WorldClockCity("America/Anchorage", "Alaska (AKST)", "❄️", "UTC-9"),
        WorldClockCity("America/Los_Angeles", "Los Angeles", "🇺🇸", "UTC-8"),
        WorldClockCity("America/Vancouver", "Vancouver", "🇨🇦", "UTC-8"),
        WorldClockCity("America/Tijuana", "Tijuana", "🇲🇽", "UTC-8"),
        WorldClockCity("America/Denver", "Denver", "🇺🇸", "UTC-7"),
        WorldClockCity("America/Phoenix", "Phoenix", "🇺🇸", "UTC-7"),
        WorldClockCity("America/Calgary", "Calgary", "🇨🇦", "UTC-7"),
        WorldClockCity("America/Chicago", "Chicago", "🇺🇸", "UTC-6"),
        WorldClockCity("America/Mexico_City", "Mexico City", "🇲🇽", "UTC-6"),
        WorldClockCity("America/Winnipeg", "Winnipeg", "🇨🇦", "UTC-6"),
        WorldClockCity("America/New_York", "New York", "🇺🇸", "UTC-5"),
        WorldClockCity("America/Toronto", "Toronto", "🇨🇦", "UTC-5"),
        WorldClockCity("America/Lima", "Lima", "🇵🇪", "UTC-5"),
        WorldClockCity("America/Bogota", "Bogotá", "🇨🇴", "UTC-5"),
        WorldClockCity("America/Halifax", "Halifax", "🇨🇦", "UTC-4"),
        WorldClockCity("America/Caracas", "Caracas", "🇻🇪", "UTC-4"),
        WorldClockCity("America/La_Paz", "La Paz", "🇧🇴", "UTC-4"),
        WorldClockCity("America/Santiago", "Santiago", "🇨🇱", "UTC-4"),
        WorldClockCity("America/Sao_Paulo", "São Paulo", "🇧🇷", "UTC-3"),
        WorldClockCity("America/Argentina/Buenos_Aires", "Buenos Aires", "🇦🇷", "UTC-3"),
        WorldClockCity("America/Montevideo", "Montevideo", "🇺🇾", "UTC-3"),
        WorldClockCity("America/Noronha", "South Georgia", "🇬🇸", "UTC-2"),
        WorldClockCity("Atlantic/Azores", "Azores", "🇵🇹", "UTC-1"),
        WorldClockCity("Atlantic/Cape_Verde", "Cape Verde", "🇨🇻", "UTC-1"),
        WorldClockCity("Europe/London", "London (GMT/BST)", "🇬🇧", "UTC+0"),
        WorldClockCity("Europe/Dublin", "Dublin", "🇮🇪", "UTC+0"),
        WorldClockCity("Europe/Lisbon", "Lisbon", "🇵🇹", "UTC+0"),
        WorldClockCity("Atlantic/Reykjavik", "Reykjavik", "🇮🇸", "UTC+0"),
        WorldClockCity("Africa/Accra", "Accra", "🇬🇭", "UTC+0"),
        WorldClockCity("Europe/Paris", "Paris", "🇫🇷", "UTC+1"),
        WorldClockCity("Europe/Berlin", "Berlin", "🇩🇪", "UTC+1"),
        WorldClockCity("Europe/Rome", "Rome", "🇮🇹", "UTC+1"),
        WorldClockCity("Europe/Madrid", "Madrid", "🇪🇸", "UTC+1"),
        WorldClockCity("Europe/Amsterdam", "Amsterdam", "🇳🇱", "UTC+1"),
        WorldClockCity("Africa/Lagos", "Lagos", "🇳🇬", "UTC+1"),
        WorldClockCity("Africa/Casablanca", "Casablanca", "🇲🇦", "UTC+1"),
        WorldClockCity("Africa/Cairo", "Cairo", "🇪🇬", "UTC+2"),
        WorldClockCity("Europe/Athens", "Athens", "🇬🇷", "UTC+2"),
        WorldClockCity("Africa/Johannesburg", "Johannesburg", "🇿🇦", "UTC+2"),
        WorldClockCity("Europe/Helsinki", "Helsinki", "🇫🇮", "UTC+2"),
        WorldClockCity("Europe/Kiev", "Kyiv", "🇺🇦", "UTC+2"),
        WorldClockCity("Europe/Bucharest", "Bucharest", "🇷🇴", "UTC+2"),
        WorldClockCity("Europe/Moscow", "Moscow", "🇷🇺", "UTC+3"),
        WorldClockCity("Asia/Riyadh", "Riyadh", "🇸🇦", "UTC+3"),
        WorldClockCity("Africa/Nairobi", "Nairobi", "🇰🇪", "UTC+3"),
        WorldClockCity("Europe/Istanbul", "Istanbul", "🇹🇷", "UTC+3"),
        WorldClockCity("Asia/Baghdad", "Baghdad", "🇮🇶", "UTC+3"),
        WorldClockCity("Asia/Kuwait", "Kuwait", "🇰🇼", "UTC+3"),
        WorldClockCity("Asia/Tehran", "Tehran", "🇮🇷", "UTC+3:30"),
        WorldClockCity("Asia/Dubai", "Dubai", "🇦🇪", "UTC+4"),
        WorldClockCity("Asia/Baku", "Baku", "🇦🇿", "UTC+4"),
        WorldClockCity("Asia/Tbilisi", "Tbilisi", "🇬🇪", "UTC+4"),
        WorldClockCity("Asia/Yerevan", "Yerevan", "🇦🇲", "UTC+4"),
        WorldClockCity("Indian/Mauritius", "Port Louis", "🇲🇺", "UTC+4"),
        WorldClockCity("Asia/Kabul", "Kabul", "🇦🇫", "UTC+4:30"),
        WorldClockCity("Asia/Karachi", "Karachi", "🇵🇰", "UTC+5"),
        WorldClockCity("Asia/Tashkent", "Tashkent", "🇺🇿", "UTC+5"),
        WorldClockCity("Asia/Yekaterinburg", "Yekaterinburg", "🇷🇺", "UTC+5"),
        WorldClockCity("Asia/Kolkata", "India (IST) – New Delhi", "🇮🇳", "UTC+5:30"),
        WorldClockCity("Asia/Kathmandu", "Nepal (NPT) – Kathmandu", "🇳🇵", "UTC+5:45"),
        WorldClockCity("Asia/Dhaka", "Dhaka", "🇧🇩", "UTC+6"),
        WorldClockCity("Asia/Almaty", "Almaty", "🇰🇿", "UTC+6"),
        WorldClockCity("Asia/Colombo", "Colombo", "🇱🇰", "UTC+6"),
        WorldClockCity("Asia/Yangon", "Yangon (Myanmar)", "🇲🇲", "UTC+6:30"),
        WorldClockCity("Asia/Bangkok", "Bangkok", "🇹🇭", "UTC+7"),
        WorldClockCity("Asia/Jakarta", "Jakarta", "🇮🇩", "UTC+7"),
        WorldClockCity("Asia/Ho_Chi_Minh", "Ho Chi Minh City", "🇻🇳", "UTC+7"),
        WorldClockCity("Asia/Novosibirsk", "Novosibirsk", "🇷🇺", "UTC+7"),
        WorldClockCity("Asia/Shanghai", "Beijing", "🇨🇳", "UTC+8"),
        WorldClockCity("Asia/Singapore", "Singapore", "🇸🇬", "UTC+8"),
        WorldClockCity("Asia/Kuala_Lumpur", "Kuala Lumpur", "🇲🇾", "UTC+8"),
        WorldClockCity("Australia/Perth", "Perth", "🇦🇺", "UTC+8"),
        WorldClockCity("Asia/Manila", "Manila", "🇵🇭", "UTC+8"),
        WorldClockCity("Asia/Taipei", "Taipei", "🇹🇼", "UTC+8"),
        WorldClockCity("Australia/Eucla", "Eucla (Australia)", "🇦🇺", "UTC+8:45"),
        WorldClockCity("Asia/Tokyo", "Tokyo", "🇯🇵", "UTC+9"),
        WorldClockCity("Asia/Seoul", "Seoul", "🇰🇷", "UTC+9"),
        WorldClockCity("Asia/Pyongyang", "Pyongyang", "🇰🇵", "UTC+9"),
        WorldClockCity("Asia/Yakutsk", "Yakutsk", "🇷🇺", "UTC+9"),
        WorldClockCity("Australia/Adelaide", "Adelaide", "🇦🇺", "UTC+9:30"),
        WorldClockCity("Australia/Darwin", "Darwin (ACST)", "🇦🇺", "UTC+9:30"),
        WorldClockCity("Australia/Sydney", "Sydney", "🇦🇺", "UTC+10"),
        WorldClockCity("Australia/Melbourne", "Melbourne", "🇦🇺", "UTC+10"),
        WorldClockCity("Australia/Brisbane", "Brisbane", "🇦🇺", "UTC+10"),
        WorldClockCity("Asia/Vladivostok", "Vladivostok", "🇷🇺", "UTC+10"),
        WorldClockCity("Pacific/Guam", "Guam", "🇬🇺", "UTC+10"),
        WorldClockCity("Australia/Lord_Howe", "Lord Howe Island", "🇦🇺", "UTC+10:30"),
        WorldClockCity("Pacific/Guadalcanal", "Solomon Islands", "🇸🇧", "UTC+11"),
        WorldClockCity("Pacific/Noumea", "Noumea", "🇳🇨", "UTC+11"),
        WorldClockCity("Asia/Magadan", "Magadan", "🇷🇺", "UTC+11"),
        WorldClockCity("Pacific/Auckland", "Auckland", "🇳🇿", "UTC+12"),
        WorldClockCity("Pacific/Fiji", "Fiji", "🇫🇯", "UTC+12"),
        WorldClockCity("Asia/Kamchatka", "Kamchatka", "🇷🇺", "UTC+12"),
        WorldClockCity("Pacific/Funafuti", "Tuvalu", "🇹🇻", "UTC+12"),
        WorldClockCity("Pacific/Chatham", "Chatham Islands", "🇳🇿", "UTC+12:45"),
        WorldClockCity("Pacific/Apia", "Samoa (independent)", "🇼🇸", "UTC+13"),
        WorldClockCity("Pacific/Tongatapu", "Tonga", "🇹🇴", "UTC+13"),
        WorldClockCity("Pacific/Enderbury", "Phoenix Islands", "🇰🇮", "UTC+13"),
        WorldClockCity("Pacific/Kiritimati", "Line Islands (Kiribati)", "🇰🇮", "UTC+14")
    )
}
